### ISSUE TITLE
angeError [ERR_OUT_OF_RANGE] on clinic bubbleprof

### ISSUE THREAD

**Issue by aldarund** [clinicjs/node-clinic#188]
## Current Behavior
RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 65535. Received 136030
    at checkInt (internal/buffer.js:58:11)
    at writeU_Int16BE (internal/buffer.js:818:3)
    at Buffer.writeUInt16BE (internal/buffer.js:826:10)
    at StackTraceEncoder._transform (c:\Users\shape\AppData\Roaming\npm\node_modules\clinic\node_modules\@nearform\bubbleprof\format\abstract-encoder.js:21:19)
    at StackTraceEncoder.Transform._read (_stream_transform.js:189:10)
    at StackTraceEncoder.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:428:12)
    at writeOrBuffer (_stream_writable.js:412:5)
    at StackTraceEncoder.Writable.write (_stream_writable.js:302:11)
    at AsyncHook.init (c:\Users\shape\AppData\Roaming\npm\node_modules\clinic\node_modules\@nearform\bubbleprof\injects\logger.js:45:13)

## Steps to Reproduce (for bugs)
it happen when i try to debug real nuxtjs typescript project. After like 3-5-10 seconds it crashes with that error

## Sample upload
https://www.dropbox.com/s/8i6pnkmn1u257tg/.clinic.zip?dl=0

## Environment

* Clinic.js version: 4.1

* Node.js version: 12.10

* Browser name and version:

Win 10

**Comment by aldarund** [comment]
It dont happen on empty project, but happens on real private project... So cant really provide full repro :(

**Comment by DylanC** [comment]
@aldarund - Have a look at my answer on #189. You are likely having the same issue.
