### ISSUE TITLE
Cannot use for Rocket.Chat - doesn't generate traceevent file

### ISSUE THREAD

**Issue by sampaiodiego** [clinicjs/node-clinic#268]
## Expected Behavior

After running `clinic doctor` open the UI showing the results.

## Current Behavior

Hitting Ctrl + C shows the following error message:
```
[=   ] Received Ctrl+C, closing process...Error: No files matching the pattern found
    at notFound (/Users/diegosampaio/.nvm/versions/node/v12.18.3/lib/node_modules/clinic/node_modules/@nearform/node-trace-log-join/index.js:66:15)
    at combine (/Users/diegosampaio/.nvm/versions/node/v12.18.3/lib/node_modules/clinic/node_modules/@nearform/node-trace-log-join/index.js:25:34)
    at /Users/diegosampaio/.nvm/versions/node/v12.18.3/lib/node_modules/clinic/node_modules/@nearform/node-trace-log-join/index.js:21:5
    at FSReqCallback.oncomplete (fs.js:156:23)
```

## Steps to Reproduce (for bugs)

1. Build Rocket.Chat
2. Run it using `clinic doctor`
3. Exit hitting `Ctrl + C`

## Environment

* Clinic.js version: v7.0.0

* Node.js version: v12.18.3

* Browser name and version:

* Operating system and version: macOS 10.15.5

**Comment by shahyar** [comment]
See my edit here for how this is happening https://github.com/clinicjs/node-clinic/issues/10#issuecomment-752276911
The files are simply in the path defined by `chdir` in `main.js`.

Off-topic: I've successfully started profiling Rocket.Chat, and the MongoDB connection stuff is looking very bad.

**Comment by bradphelan** [comment]
I see the same error.

```
D:\sandboxes\start-stop\server [master ≡ +2 ~3 -0 !]> npx clinic bubbleprof -- node build/server.js
To generate the report press: Ctrl + C
No env file present for the current environment:  undefined
 Falling back to .env config
No env file present for the current environment:  undefined
Config {
  env: 'development',
  port: 3000,
  protocol: 'http',
  hostName: 'localhost',
  keyFile: '',
  certFile: ''
}
using dev build
[HPM] Proxy created: /  -> http://localhost:8080
Server is running, GraphQL Playground available at https://caluan-ematt.moduleworks.com:3000/graphql
[    ] Received Ctrl+C, closing process...^CTerminate batch job (Y/N)? process exited with exit code 1
Error: No files matching the pattern found
    at notFound (C:\Users\brad\AppData\Roaming\npm\node_modules\clinic\node_modules\@nearform\node-trace-log-join\index.js:66:15)
    at combine (C:\Users\brad\AppData\Roaming\npm\node_modules\clinic\node_modules\@nearform\node-trace-log-join\index.js:25:34)
    at C:\Users\brad\AppData\Roaming\npm\node_modules\clinic\node_modules\@nearform\node-trace-log-join\index.js:21:5
    at FSReqCallback.oncomplete (fs.js:164:23)
```
