### ISSUE TITLE
SyntaxError: Missing initializer in const declaration

### ISSUE THREAD

**Issue by alphabetkrish** [clinicjs/node-clinic#270]
## Expected Behavior

 clinic doctor -- node  server.js should create performance profiling without any issue
 
## Current Behavior
Error - SyntaxError: Missing initializer in const declaration is thrown

 clinic doctor -- node  server.js
To generate the report press: Ctrl + C
dev
/Users/pshunmug/Automation/temp/tempone/forkedcopy/availability-eventdriven-platform/application/controllers/loadDataController.ts:61
            const response: {queryDate: string, status: string, error?:string} = {
                  ^^^^^^^^

SyntaxError: Missing initializer in const declaration
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)

## Steps to Reproduce (for bugs)

1. Run  clinic doctor -- node  server.js

## Environment
*ClinicJs version
clinic -v
v7.0.0
clinic doctor -v
v6.0.0

* Node.js version:

node -v
v12.16.1
npm -v
6.13.4

* Operating system and version:
MacOs Catalina 10.15.17

**Comment by alphabetkrish** [comment]
W/a provided in Issue #226  doesn't help :-(
