### ISSUE TITLE
clinic flame Error: EEXIST: file already exists, uv_pipe_open

### ISSUE THREAD

**Issue by special-character** [clinicjs/node-clinic#276]
## Current Behavior

When I run `clinic flame` for my server, it crashes on startup with the error:

```
net.js:269
    err = this._handle.open(fd);
                       ^

Error: EEXIST: file already exists, uv_pipe_open
    at new Socket (net.js:269:24)
    at Object.<anonymous> (/Users/brandonroberts/.config/yarn/global/node_modules/0x/lib/preload/redir-stdout.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:901:12)
    at preloadModules (internal/bootstrap/node.js:602:7)
```

I run it with the command:
```
clinic flame --on-port 'autocannon localhost:$PORT' -- node ../node_modules/.bin/nexus dev
```

## Expected Behavior
Running the flame profiler would not crash on startup.

## Steps to Reproduce (for bugs)
1. Run clinic flame with autocannon option

I don't have a small repro yet but can work on one

## Sample upload
[logs.zip](https://github.com/clinicjs/node-clinic/files/5789829/logs.zip)

## Environment
* Clinic.js version:v8.0.1 Doctor: v7.0.1
* Node.js version:v10.23.0
* Browser name and version: Didn't get this far
* Operating system and version: OS X 10.15.7

**Comment by mcollina** [comment]
I'm not necessarily sure what nexus is, but likely this problem is caused by something that nexus does that clinic does not like. It would be very helpful if you could upload an example repro to reproduce the problem.

**Comment by special-character** [comment]
@mcollina Sure thing, thanks for looking. I will check back in and update when I have a good small repro

**Comment by liamaharon** [comment]
FYI I had this issue when using Clinic Flame on a project that used child processes. Moving everything onto the same process made the err to go away.

**Comment by KyleAMathews** [comment]
Hit the same error with child processses
