### ISSUE TITLE
Analysing dataError: Encountered an unparseable frame "wasm-to-js:iiii:i [WASM:Builtin] [INIT]"

### ISSUE THREAD

**Issue by stavalfi** [clinicjs/node-clinic#291]
Command:
```
CSM_IM_HARD_CODED_PUNTEAM_TOPIC=1_20211022110721 APP_ENV=local-devk8s clinic flame -- node -r ./.pnp.cjs packages/csm-im/dist/src/index.js
```

output:
```
....app logs
.....
ctrl+c
[    ] Analysing dataError: Encountered an unparseable frame "wasm-to-js:iiii:i [WASM:Builtin] [INIT]"
    at new FrameNode (/Users/stavalfi/.fnm/node-versions/v14.15.4/installation/lib/node_modules/clinic/node_modules/@nearform/flame/analysis/frame-node.js:86:15)
    at /Users/stavalfi/.fnm/node-versions/v14.15.4/installation/lib/node_modules/clinic/node_modules/@nearform/flame/analysis/frame-node.js:19:38
    at Array.map (<anonymous>)
    at new FrameNode (/Users/stavalfi/.fnm/node-versions/v14.15.4/installation/lib/node_modules/clinic/node_modules/@nearform/flame/analysis/frame-node.js:19:23)
    at /Users/stavalfi/.fnm/node-versions/v14.15.4/installation/lib/node_modules/clinic/node_modules/@nearform/flame/analysis/frame-node.js:19:38
    at Array.map (<anonymous>)
    at new FrameNode (/Users/stavalfi/.fnm/node-versions/v14.15.4/installation/lib/node_modules/clinic/node_modules/@nearform/flame/analysis/frame-node.js:19:23)
    at /Users/stavalfi/.fnm/node-versions/v14.15.4/installation/lib/node_modules/clinic/node_modules/@nearform/flame/analysis/frame-node.js:19:38
    at Array.map (<anonymous>)
    at new FrameNode (/Users/stavalfi/.fnm/node-versions/v14.15.4/installation/lib/node_modules/clinic/node_modules/@nearform/flame/analysis/frame-node.js:19:23)
```

## Steps to Reproduce (for bugs)
private repository

## Environment
```
stavalfi@stavs-MacBook-Pro ~/p/singer (stav/wip353)> clinic -v
v9.0.0
stavalfi@stavs-MacBook-Pro ~/p/singer (stav/wip353)> clinic doctor -v
v8.0.0
stavalfi@stavs-MacBook-Pro ~/p/singer (stav/wip353)> node -v
v14.15.4
stavalfi@stavs-MacBook-Pro ~/p/singer (stav/wip353)> npm -v
6.14.10
stavalfi@stavs-MacBook-Pro ~/p/singer (stav/wip353)> yarn -v
3.1.0-rc.4
stavalfi@stavs-MacBook-Pro ~/p/singer (stav/wip353)> chrome Version 95.0.4638.54 (Official Build) (x86_64)
stavalfi@stavs-MacBook-Pro ~/p/singer (stav/wip353) [255]> echo macos bigsur 11.5.2 (20G95)
```

* I installed clinic without yarn: `npm i -g clinic`

[.clinic.zip](https://github.com/clinicjs/node-clinic/files/7408766/default.clinic.zip)

**Comment by RafaelGSS** [comment]
Hi, @stavalfi thanks for pointing it out. It should be fixed when [8.0.1](https://github.com/clinicjs/node-clinic-bubbleprof/pull/391) version lands. Check it out, if it still doesn't work, open a new issue with a reproducible example, please.
