### ISSUE TITLE
`clinic flame` crashes with an `unparseable frame` error on functions with a backslash in their name

### ISSUE THREAD

**Issue by merceyz** [clinicjs/node-clinic#327]
## Expected Behavior

The flame graph should be successfully generated

## Current Behavior

It crashes with an unparseable frame error

```sh
$ clinic flame -- node ./foo.js
To generate the report press: Ctrl + C
[    ] Analysing dataError: Encountered an unparseable frame "foo
app/foo.js:2:12"
    at new FrameNode (/usr/local/lib/node_modules/clinic/node_modules/@clinic/flame/analysis/frame-node.js:86:15)
    at /usr/local/lib/node_modules/clinic/node_modules/@clinic/flame/analysis/frame-node.js:19:38
    at Array.map (<anonymous>)
    at new FrameNode (/usr/local/lib/node_modules/clinic/node_modules/@clinic/flame/analysis/frame-node.js:19:23)
    at /usr/local/lib/node_modules/clinic/node_modules/@clinic/flame/analysis/frame-node.js:19:38
    at Array.map (<anonymous>)
    at new FrameNode (/usr/local/lib/node_modules/clinic/node_modules/@clinic/flame/analysis/frame-node.js:19:23)
    at /usr/local/lib/node_modules/clinic/node_modules/@clinic/flame/analysis/frame-node.js:19:38
    at Array.map (<anonymous>)
    at new FrameNode (/usr/local/lib/node_modules/clinic/node_modules/@clinic/flame/analysis/frame-node.js:19:23)
```

## Steps to Reproduce (for bugs)

1. Create a file with the following content
```js
const obj = {
	'foo\\bar'() {
		// Do some work to show up in the flame graph
		for (let i = 0; i < 1000; i++) {
			require('crypto').randomUUID();
		}
	},
};

obj['foo\\bar']();
```
2. Run `clinic flame -- node ./foo.js`

## Sample upload
N/A

## Environment

* Clinic.js version:
```
$ clinic -v
v11.0.0
$ clinic flame -v
v11.0.0 (0x v5.0.0)
```

* Node.js version:
```
$ node -v 
v16.13.2
$ npm -v
8.1.2
```

* Browser name and version:
N/A

* Operating system and version:
```
Linux 951e9191a966 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 GNU/Linux
Linux 5.10 Debian GNU/Linux 10 (buster) 10 (buster)
```

**Comment by mcollina** [comment]
wow! Nice finding
