### ISSUE TITLE
Heap profile is empty inside docker container

### ISSUE THREAD

**Issue by dcharp05** [clinicjs/node-clinic#341]
## Expected Behavior
Commands other than the doctor command work inside docker containers.

## Current Behavior
I am running node clinic with a project at work. The doctor command work find and outputs files with data. If I try any other command the output files are empty. Has anyone been able to run this successfully in side docker?
## Steps to Reproduce (for bugs)
Running `./node_modules/.bin/clinic ${doctorMode} -- node --max-old-space-size=4096` inside the container, where dockerMode is one of the available commands.

## Sample upload
File is empty

## Environment
docker-image - > node:14.18.2-alpine
latest clinic version

* Node.js version:
Node 14.18.2
* Browser name and version:
Chrome 97

Host OS is Ubuntu x86_64 x86_64 x86_64 GNU/Linux

**Comment by RafaelGSS** [comment]
Try one of the approaches mentioned in https://github.com/clinicjs/node-clinic/issues/10

**Comment by dcharp05** [comment]
Yes I saw that thread. The heap profile will start up, but when I kill the process the file is empty and I am not seeing any errors or logs.

**Comment by robross0606** [comment]
I am seeing the same problem without using a docker container.  I tried using the `timeout --signal=SIGINT 20s` approach and got an exception:
```
Error [ERR_INSPECTOR_NOT_CONNECTED]: Session is not connected
    at new NodeError (internal/errors.js:322:7)
    at Session.post (inspector.js:108:13)
    at AbortSignal.finish (/usr/lib/node_modules/clinic/node_modules/@nearform/heap-profiler/src/profile.js:56:13)
    at AbortSignal.dispatchEvent (/usr/lib/node_modules/clinic/node_modules/event-target-shim/dist/event-target-shim.js:818:35)
    at abortSignal (/usr/lib/node_modules/clinic/node_modules/abort-controller/dist/abort-controller.js:52:12)
    at AbortController.abort (/usr/lib/node_modules/clinic/node_modules/abort-controller/dist/abort-controller.js:91:9)
    at process.stopSampling (/usr/lib/node_modules/clinic/node_modules/@clinic/heap-profiler/src/injects/ipc.js:23:14)
    at Object.onceWrapper (events.js:520:26)
    at process.emit (events.js:412:35) {
  code: 'ERR_INSPECTOR_NOT_CONNECTED'
}
```
Heap profile file was still empty.

**Comment by Stono** [comment]
I am more than willing to bet you're hitting https://github.com/clinicjs/node-clinic/issues/444#issuecomment-1474997090

**Comment by robross0606** [comment]
It is most likely similar, but I think there is also an extra problem with doing this on Windows due to the unique way it handles signals.
