### ISSUE TITLE
Error: No matching files matching the pattern found

### ISSUE THREAD

**Issue by vaditya92** [clinicjs/node-clinic#415]
Hi. I am trying to use clinic doctor to analyse my application. Unfortunately, I am facing an error that I am not able to resolve.

```clinic doctor -- node server/index.js 
To generate the report press: Ctrl + C
2021-01-06T10:45:35.665Z info: master http@3001 Using config file(s): /home/adityav/Documents/workspace/wfm/config/config.cjson
2021-01-06T10:45:35.666Z info: master http@3001 Environment: development
2021-01-06T10:45:35.670Z log: master http@3001 Starting 1 worker (1)
2021-01-06T10:45:35.672Z log: master http@3001 Worker clinicjs/node-clinic-doctor#1 started (pid 15915)
Watching these locations for changes:
  /home/adityav/Documents/workspace/wfm/server/lib/**/*.js
  /home/adityav/Documents/workspace/wfm/config/{development,common}.*json
2021-01-06T10:45:36.288Z log: master http@3001 Worker clinicjs/node-clinic-doctor#1 (pid 15915) STDERR: 2021-01-06T10:45:36.287Z log: Worker clinicjs/node-clinic-doctor#1 (pid 15915) http@3001 Launched worker on http://0.0.0.0:3001/
2021-01-06T10:45:36.289Z log: master http@3001 Worker clinicjs/node-clinic-doctor#1 (pid 15915) STDERR: 2021-01-06T10:45:36.289Z log: Worker clinicjs/node-clinic-doctor#1 (pid 15915) http@3001 Listening on http://0.0.0.0:3001/
^C[    ] Received Ctrl+C, closing process...Error: No files matching the pattern found
    at notFound (/home/adityav/.nvm/versions/node/v14.15.0/lib/node_modules/clinic/node_modules/@nearform/node-trace-log-join/index.js:66:15)
    at combine (/home/adityav/.nvm/versions/node/v14.15.0/lib/node_modules/clinic/node_modules/@nearform/node-trace-log-join/index.js:25:34)
    at /home/adityav/.nvm/versions/node/v14.15.0/lib/node_modules/clinic/node_modules/@nearform/node-trace-log-join/index.js:21:5
    at FSReqCallback.oncomplete (fs.js:171:23)```

Platform: Linux Ubuntu(18.04.5)
Node: v14.15.0

**Comment by chaospixel** [comment]
I'm also seeing this. I'm assuming I'm doing something wrong, but it's unclear what...
