### ISSUE TITLE
Be resilient against unexpected end of JSON input

### ISSUE THREAD

**Issue by mcollina** [clinicjs/node-clinic#430]
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Parser._flush (/Users/matteo/.nvm/versions/node/v10.14.2/lib/node_modules/clinic/node_modules/@nearform/trace-events-parser/index.js:58:24)
    at Parser.prefinish (_stream_transform.js:141:10)
    at Parser.emit (events.js:182:13)
    at prefinish (_stream_writable.js:630:14)
    at finishMaybe (_stream_writable.js:638:5)
    at endWritable (_stream_writable.js:649:3)
    at Parser.Writable.end (_stream_writable.js:589:5)
    at ReadStream.onend (_stream_readable.js:628:10)
    at Object.onceWrapper (events.js:273:13)
```

**Comment by Stono** [comment]
Same issue here, can't sus this one out!

**Comment by Stono** [comment]
So this is caused by having `'--trace-events-enabled', '--trace-event-categories', 'v8'` where the doctor spawns the process.  `v18.14.2` btw.

Looks to be https://github.com/nodejs/node/issues/22042?

**Comment by Stono** [comment]
OK digging further this only happens in apps for us that include `@google-cloud/resource-manager`

**Comment by Stono** [comment]
Raised: https://github.com/googleapis/google-cloud-node/issues/4384
Not sure of the underlying cause however, hopefully the developers of that library will have a clue which helps others

**Comment by Stono** [comment]
Also raised https://github.com/nodejs/node/issues/48598, I think this is the root cause of the bug. 

In doctor, it causes a SIGABRT because of this line: https://github.com/clinicjs/node-clinic-doctor/blob/00749d83f04cb30ed24e91f29e89ad25e267ac33/injects/sampler.js#L22

**Comment by Stono** [comment]
interestingly this isn't a problem on node16, only 18

**Comment by magnusburton** [comment]
> interestingly this isn't a problem on node16, only 18

Currently experiencing this on latest versions of 16, 18, 20, and 21.
